name: expense_repository
description: The repo that handles expenses
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  #sdk: '^3.6.0'

dependencies: 
  flutter:
    sdk: flutter

  #firebase_auth: ^4.16.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  #cloud_firestore: ^4.9.2
  #rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true